import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "./components/MainLayout";
import MenuContextProvider from "./components/context/MenuContext";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { TanStackProvider } from "./components/providers/TanStackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemesProvider attribute="class" defaultTheme="system" enableSystem>
          <TanStackProvider>
            <MenuContextProvider>
              <MainLayout>
                {children}
              </MainLayout>
            </MenuContextProvider>
          </TanStackProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
